branchName: '#${issue.number}'
branches:
  - label: '✨ Feature'
    prefix: feat/
  - label: '🔨 Refactor'
    prefix: refactor/
  - label: '✅ Test'
    prefix: test/
  - label: '📃 Docs'
    prefix: docs/
  - label: '⚙ Setting'
    prefix: setting/
  - label: '🌏 Deploy'
    prefix: deploy/
  - label: '🎨 Design'
    prefix: design/
  - label: '🐞 BugFix'
    prefix: bugfix/
  - label: '📬 API'
    prefix: api/
  - label: '🙋‍♂️ Question'
    prefix: question/
autoCloseIssue: true
commentMessage: '✅ 자동 생성된 브랜치: `${branchName}` 이슈: ${issue.title}'
transform:
  issue.title:
    pattern: '[^a-zA-Z0-9]+'
    replacement: '-'
    toLower: true
