blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: ✨ Feature
    description: 새로운 기능 개발을 위한 이슈
    file: feature-request.yml

  - name: 🐞 BugFix
    description: 버그 수정 작업을 위한 이슈
    file: Bug-Report.yml

  - name: 🔨 Refactor
    description: 코드 리팩토링 작업 이슈
    file: refactor-task.yml

  - name: 📃 Docs
    description: 문서 작성 및 수정 작업 이슈
    file: docs-task.yml

  - name: ⚙ Setting
    description: 개발 환경 설정 관련 이슈
    file: setting-task.yml

  - name: 🌏 Deploy
    description: 배포 관련 작업을 위한 이슈
    file: deploy-task.yml

  - name: 🎨 Design
    description: UI 디자인 작업을 위한 이슈
    file: design-task.yml

  - name: 📬 API
    description: 서버 API 통신 관련 작업
    file: api-task.yml

  - name: 🙋‍♂️ Question
    description: 추가 설명이 필요한 질문 또는 논의
    file: question-form.yml

  - name: ✅ Test
    description: 테스트 코드 작성 및 테스트 환경 구축
    file: test-task.yml
