name: Design Task
description: UI 디자인 작업을 위한 이슈 템플릿입니다.
title: "[Design] "
labels: ["🎨 Design"]
body:
  - type: input
    id: description
    attributes:
      label: "🎨 디자인 설명"
      description: "작업할 UI 디자인 요소에 대해 설명해주세요"
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: "📐 디자인 작업 목록"
      description: "진행할 디자인 작업들을 작성해주세요"
      value: |
        - [ ] 디자인 시안 작성
        - [ ] Figma 공유
    validations:
      required: true

  - type: input
    id: links
    attributes:
      label: "🔗 참고 링크"
      description: "Figma 링크, 레퍼런스 UI 등이 있다면 첨부해주세요 (선택)"
      placeholder: "https://..."
    validations:
      required: false
