name: Auto Assign Reviewers and Assignees

on:
  pull_request:
    types: [opened]

jobs:
  assign-reviewers-and-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers (excluding author)
        uses: peter-evans/reviewers@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: |
            doyeonk429
            yeseonglee
            dlguszoo
          filter-author: true

      - name: Assign assignees (including author if needed)
        uses: peter-evans/auto-assign@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            doyeonk429
            yeseonglee
            dlguszoo
          filter-author: false  # true로 하면 PR 작성자는 제외됨
